In [1]:
import tensorflow as tf
node1 = tf.constant([[3.0,1.5],[2.5,6.0]], tf.float32)
node2 = tf.constant([[4.0,1.0],[5.0,2.5]], tf.float32)
node3 = tf.add(node1, node2)
print (node3)

tf.Tensor(
[[7.  2.5]
 [7.5 8.5]], shape=(2, 2), dtype=float32)


In [2]:
print(node1)

tf.Tensor(
[[3.  1.5]
 [2.5 6. ]], shape=(2, 2), dtype=float32)


In [3]:
print(node3.numpy())

[[7.  2.5]
 [7.5 8.5]]
